version: "3.8"
services:
  backend:
    image: "ramanado/springboot-react-fullstack:23.3.2021.18.5.23"
    ports:
    - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      RDS_ENDPOINT: ${RDS_ENDPOINT}
      USERNAME: ${DB_USERNAME}
      PASSWORD: ${DB_PASSWORD}
