version: "3.8"
services:
  backend:
    image: "ramanado/springboot-react-fullstack:21.3.2021.17.0.40"
    ports:
    - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev