version: "3.8"
services:
  backend:
    image: "ramanado/springboot-react-fullstack:22.3.2021.8.1.36"
    ports:
    - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev